catcollectr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('cats/', views.cats_index, name='cats_index'),
    path('cats/<int:cat_id>/', views.cats_show, name='cats_show'),
    path('cats/create/', views.CatCreate.as_view(), name='cats_create' ),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cats_update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cats_delete'),
    path('user/<username>', views.profile, name='profile'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('cattoys/', views.cattoys_index, name='cattoys_index'),
    path('cattoys/<int:cattoy_id>', views.cattoys_show, name='cattoys_show'),
    path('cattoys/create/', views.CatToyCreate.as_view(), name='cattoys_create'),
    path('cattoys/<int:pk>/update/', views.CatToyUpdate.as_view(), name='cattoys_update'),
    path('cattoys/<int:pk>/delete/', views.CatToyDelete.as_view(), name='cattoys_delete'),
    path('cats/<int:cat_id>/assoc_toy/<int:toy_id>', views.assoc_toy, name="assoc_toy"),
    path('cats/<int:cat_id>/unassoc_toy/<int:toy_id>', views.unassoc_toy, name="unassoc_toy"),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class CatToy(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    age = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cattoys = models.ManyToManyField(CatToy)

    def __str__(self):
        return self.name

main_app/views.py
from django.shortcuts import render, redirect
from .models import Cat, CatToy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# create your views (these are like your controller actions here)
############## USER ###############

def login_view(request):
    if request.method == 'POST': ## it was a POST request so send the login data when submits
        # try to login the user in
        form = AuthenticationForm(request, request.POST)
        if(form.is_valid()):
            u = form.cleaned_data['username']
            p = form.cleaned_data['password']
            user = authenticate(username=u, password=p)
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect('/user/'+u)
                else: 
                    return HttpResponse('The account has been disabled.')
            else:
                return HttpResponse('The username and/or the password is incorrect')
    else: # it was a GET request so send the empty login form
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/cats')

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect('/user/'+str(user))
        else:
            return HttpResponse('<h2>Try Again</h2>')
    else:
        form = UserCreationForm()
        return render(request, 'signup.html', {'form': form})

@login_required
def profile(request, username):
    user = User.objects.get(username= username)
    cats = Cat.objects.filter(user=user)
    return render(request, 'profile.html', {'username': username, 'cats': cats})


############## CATS #################

# django will make a create cat form for us
@method_decorator(login_required, name='dispatch')
class CatCreate(CreateView):
    model = Cat
    fields = ['name', 'breed', 'age', 'description']
    #success_url = '/cats/'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect('/cats')

class CatUpdate(UpdateView):
    model = Cat
    fields = ['name', 'breed', 'description', 'age']

    def form_valid(self, form): ## its a hook do not need to call
        self.object = form.save(commit= False) # don't post to the db until we say so
        self.object.save()
        return HttpResponseRedirect('/cats/'+str(self.object.pk))

class CatDelete(DeleteView):
    model = Cat
    success_url = '/cats'

def cats_index(request):
    cats = Cat.objects.all()
    return render(request, 'cats/index.html', {'cats': cats})

def cats_show(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    toys = CatToy.objects.all()
    return render(request, 'cats/show.html', {'cat': cat, 'toys': toys})

##############  CATTOYS  ################

def cattoys_index(request):
    cattoys = CatToy.objects.all()
    return render(request, 'cattoys/index.html', {'cattoys': cattoys})

def cattoys_show(request, cattoy_id):
    cattoy = CatToy.objects.get(id=cattoy_id)
    return render(request, 'cattoys/show.html', {'cattoy': cattoy})

class CatToyCreate(CreateView):
    model = CatToy
    fields = '__all__'
    success_url = '/cattoys'

class CatToyUpdate(UpdateView):
    model = CatToy
    fields = ['name', 'color']
    success_url = '/cattoys'

class CatToyDelete(DeleteView):
    model = CatToy
    success_url = '/cattoys'

def assoc_toy(request, cat_id, toy_id):
    Cat.objects.get(id=cat_id).cattoys.add(toy_id)
    #return HttpResponseRedirect('/cats/'+str(cat_id))
    return redirect('cats_show', cat_id=cat_id) ## Alternative wat of doing redirect

def unassoc_toy(request, cat_id, toy_id):
    Cat.objects.get(id=cat_id).cattoys.remove(toy_id)
    return HttpResponseRedirect('/cats/'+str(cat_id))

##############  DEFAULT  ################

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')



# class Cat:
#     def __init__(self, name, breed, description, age):
#         self.name = name
#         self.breed = breed
#         self.description = description
#         self.age = age

# cats = [
#     Cat('Lolo', 'tabby', 'foul little demon', 3),
#     Cat('Sachi', 'tortoise shell', 'diluted tortoise shell', 0),
#     Cat('Raven', 'black tripod', '3 legged cat', 4)
# ]

main_app/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1> About the catcollector</h1>
    <hr>
    <h3> Hire the developer, Subrata.</h3>
    <footer>All right reserved, catcollector 2018</footer>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CatCollector</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <header>
        {% if user.is_authenticated %}
            <span>
                <a href="{% url 'profile' user.username %}">Hello {{user.username}}</a>
            </span>
            <span>|</span>
            <span>
                <a href="{% url 'logout' %}">Logout</a>
            </span>
        {% else %}
            <span>
                <a href="{% url 'login' %}">Login</a>
            </span>
            <span>|</span>
            <span>
                <a href="{% url 'signup' %}">Signup</a>
            </span>
        {% endif %}
        <span>|</span>
        <a href="/cattoys/create">Add a New Cat Toy!</a>
        <span>|</span>
        <a href="/cattoys">View all Cat Toys!</a>
    </header>
    <a href="{% url 'cats_index' %}">
        <h1>catcollector</h1>
    </a>
    <hr />
    
    {% block content %}

    {% endblock %}

    <footer>
        All Rights Reserved, catcollector 2018
    </footer>
</body>
</html>

main_app/templates/base_adam.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CatCollectr</title>
    <!-- Compiled and minified CSS -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <header>
        <nav>
            <div class="nav-wrapper">
              <a href="{% url 'cats_index' %}" class="brand-logo">Cat Collector</a>
              <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
              <ul class="right hide-on-med-and-down">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'profile' user.username %}">Hello {{ user.username }}</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'signup' %}">Signup</a></li>
                {% endif %}
              </ul>
            </div>
          </nav>
          <ul class="sidenav" id="mobile-demo">
            <li><a href="/">Home</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'profile' user.username %}">Hello {{ user.username }}</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'signup' %}">Signup</a></li>
            {% endif %}
          </ul>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        All Rights Reserved, CatCollectr 2018
    </footer>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

main_app/templates/cats/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <a href="/cats/create">Add a New Cat!</a>
    <hr />
    {% for cat in cats %}
        <a href="/cats/{{cat.id}}">
            <p>Name: {{ cat.name }}</p>
        </a>
        <a href="/user/{{cat.user.username}}">
            <p>Adopted by {{cat.user.username}}</p>
        </a>
        {% if cat.age > 0 %}
            <p>Age: {{ cat.age }}</p>
        {% else %}
            <p>Age: Kitten</p>    
        {% endif %}
        <p>Breed: {{ cat.breed }}</p>
        <p>Description: {{ cat.description }}</p>
        <hr />
    {% endfor %}
{% endblock %}

main_app/templates/cats/show.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h2> Name: {{ cat.name }}</h2>
    <p> Breed: {{ cat.breed }}</p>
    <p> Description: {{ cat.description }}</p>
    <p> Age: {{ cat.age }}</p>

    <a href="{% url 'cats_update' cat.id %}">Update Details</a>
    </br>
    <a href="{% url 'cats_delete' cat.id %}">Delete This Cat</a>
    <hr />
    <div class="row">
        <div class="col s6">
        <h3>{{ cat.name }}'s Toys</h3>
        {% if cat.cattoys.count %}
            {% for toy in cat.cattoys.all %}
            <div class="card">
                <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
                </span>
                </div>
                <div class="card-action">
                <form action="{% url 'unassoc_toy' cat.id toy.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Remove</button>
                </form>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <h5>No Toys :(</h5>
        {% endif %}
        </div>
        <!-- Available toys will come after this line -->
        <div class="col s6">
        <h3>Available Toys</h3>
        {% if toys.count %}
            {% for toy in toys.all %}
            <div class="card">
                <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
                </span>
                </div>
                <div class="card-action">
                <form action="{% url 'assoc_toy' cat.id toy.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <h5>{{cat.name}} Already Has All Toys Available</h5>
        {% endif %}
        </div>
    </div>

{% endblock %}

main_app/templates/cattoys/index.html
{% extends 'base.html' %}
{% block content %}
​
<h1>Cat Toy List</h1>
​
{% for cattoy in cattoys %}
    <div>
        <a href="{% url 'cattoys_show' cattoy.id %}">
            <div class="card-content">
                <span>{{ cattoy.name }}</span>
                <p>Color: {{ cattoy.color }}</p>
            </div>
        </a>
    </div>
{% endfor %}
​
{% endblock %}

main_app/templates/cattoys/show.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <span>{{ cattoy.name }}</span>
    <p>Color: {{ cattoy.color }}</p>
    <p>Owned by:</p>
    {% for cat in cattoy.cat_set.all %}
        <p>{{cat.name}}</p>
    {% empty %}
        <p>Nobody Has This Toy</p>
    {% endfor %}
</div>


{% endblock %}

main_app/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    
    <hr />
    <a href="/cats">View All My Cats!</a>
{% endblock %}

main_app/templates/login.html
{% extends 'base.html' %}

{% block content %}

<h1>LOGIN</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Login">
</form>

{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1> Delete Cat</h1>

<p>Are you sure you want to delete this cat: {{ cat }}</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">

</form>


{% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %} # cross site request 
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>

{% endblock %}

main_app/templates/main_app/cattoy_confirm_delete.html
{% extends 'base.html' %}
​
{% block content %}
    <h1>Delete Cat Toy</h1>
​
    <h4>Are you sure you want to delete <strong>{{ cattoy }}</strong>?</h4>
​
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!">
        <a href="{% url 'cattoys_show' cattoy.id %}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/cattoy_form.html
{% extends 'base.html' %}
​
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!">
    </form>
{% endblock %}

main_app/templates/profile.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ username }}'s Collection:</h1>
    {% for cat in cats %}
        <a href="/cats/{{cat.id}}">
            <h3>{{ cat.name }}</h3>
        </a>
    {% endfor %}

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}

{% block content %}

    <h2>Sign Up</h2>
    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="SignUp">
    </form>

{% endblock %}